[package]
  cjc-version = "1.0.5"
  name = "robust_fitting"
  description = "matcang example: robust_fitting"
  version = "1.0.0"
  output-type = "executable"
  compile-option = "-O2"

[dependencies]
  matcang = { path = "../../" }